### ISSUE TITLE
AttributeError: 'Xlnk' object has no attribute 'bufmap' when installing on PYNQ-Z2

### ISSUE THREAD

**Issue by louisliuwei** [Xilinx/PYNQ-HelloWorld#18]
Pynq version: 2.5.2
Board: PYNQ-z2

an error raise up when run the last step "pynq get-notebooks pynq-helloworld -p ."

**Comment by louisliuwei** [comment]
sudo pynq get-notebooks pynq-helloworld -p . 
add root permission to run the last step, and raise another failure

pynq packge has been upgraded to v2.5.2
sudo pip3 install --upgrade setuptools
sudo pip3 install --upgrade Cython
sudo pip3 install --upgrade-strategy only-if-needed --upgrade pynq==2.5.2

**Comment by louisliuwei** [comment]
pip3 install pynq
and then
sudo pip3 install pynq-helloworld
**_ModuleNotFoundError: No module named 'pynq.utils'_**

xilinx@pynq:~$ pip3 install pynq
......
Successfully built pynq cffi numpy pandas
Installing collected packages: setuptools, pycparser, cffi, numpy, six, python-dateutil, pytz, pandas, pynq
Successfully installed cffi-1.14.3 numpy-1.19.2 pandas-1.1.2 pycparser-2.20 pynq-2.5.4 python-dateutil-2.8.1 pytz-2020.1 setuptools-50.3.0 six-1.15.0

xilinx@pynq:~$ sudo pip3 install pynq-helloworld
[sudo] password for xilinx:
Collecting pynq-helloworld
  Downloading https://files.pythonhosted.org/packages/d3/b8/b492f8041932268b71470a927b422b547716fc0a4000aa50c7f81e47431e/pynq_helloworld-2.5.2.tar.gz (4.1MB)
    100% |████████████████████████████████| 4.1MB 20kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-32nx3d1k/pynq-helloworld/setup.py", line 39, in <module>
        from pynq.utils import build_py
    ModuleNotFoundError: No module named 'pynq.utils'

**Comment by yunqu** [comment]
Try to run everything in super user. 

```
su
```
then
```
pip3 install --upgrade --upgrade-strategy only-if-needed pynq
pip3 install pynq-helloworld
```

**Comment by goekce** [comment]
@yunqu thank you.
running `pynq get-notebooks pynq-helloworld -p .` with `sudo` solved the problem for me.
