### ISSUE TITLE
pip3 install fails ModuleNotFound error

### ISSUE THREAD

**Issue by burkejoh** [Xilinx/PYNQ-HelloWorld#19]
On PYNQ 2.5 
REVISION : Release 2019_10_03 3f63450
Board: ZCU104

Brand new install on new SD supplied with board

Run from terminal: sudo pip3 install pynq-helloworld

returns:

edited to here:
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-5lwuk5f6/pynq-helloworld/setup.py", line 39, in <module>
        from pynq.utils import build_py
    ModuleNotFoundError: No module named 'pynq.utils'

**Comment by yunqu** [comment]
Upgrade your `pynq` to at least v2.5.1. You can do `sudo pip3 install pynq` first.

**Comment by burkejoh** [comment]
Thanks for the quick response.

When I try to update pynq as suggested I get:
Requirement already satisfied: pynq in
/usr/local/lib/python3.6/dist-packages
Requirement already satisfied: matplotlib in /usr/lib/python3/dist-packages
(from pynq)
Requirement already satisfied: pyeda in
/usr/local/lib/python3.6/dist-packages (from pynq)
Requirement already satisfied: pytest in /usr/lib/python3/dist-packages
(from pynq)
Requirement already satisfied: pygraphviz in /usr/lib/python3/dist-packages
(from pynq)
Requirement already satisfied: setuptools>=24.2.0 in
/usr/lib/python3/dist-packages (from pynq)
Requirement already satisfied: cffi in /usr/lib/python3/dist-packages (from
pynq)
Requirement already satisfied: Pillow>=5.0.0 in
/usr/lib/python3/dist-packages (from pynq)
Requirement already satisfied: pandas in /usr/lib/python3/dist-packages
(from pynq)
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages
(from pynq)
Then the update stops.
Please advise.

**Comment by yunqu** [comment]
Try `sudo pip3 install pynq==2.5.1`

**Comment by burkejoh** [comment]
I went the pynq python source code repo on github and found the command:

sudo pip3 install --upgrade --upgrade-strategy only-if-needed pynq

This bumped me up to 2.5.4 and I was able to get helloworld running.
Thanks again.
